FROM microsoft/dotnet:2.2-runtime-stretch-slim

ARG branch=master

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        unzip \
        libunwind8 \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir deathclock
ADD https://github.com/RichTeaMan/DeathClock/archive/$branch.tar.gz deathclock.tar.gz
RUN tar -xzf deathclock.tar.gz --strip-components=1 -C deathclock
WORKDIR /deathclock
RUN ./cake.sh -target=build
ENTRYPOINT ./cake.sh -target=Web-UI -deathClockData="/json/tmdbDeathClockData.json,/json/WikiDeathClockData.json,/json/WikiStubDeathClockData.json"
